// The marks on the two maps: country, places, the campfire and the hall, and
// the things in the sea. Each is a small grid and a palette; tools/draw-blocks
// trims, enlarges by whole pixels and outlines them.
const P = (text) => Object.fromEntries(text.trim().split(/\s+/).map((pair) => pair.split('=')));

const STONE = 's=#8a8a8a S=#6a6a6a d=#4a4a4a w=#f4f8fc W=#cfdbe6';
const TREE = 'l=#3f8a2a L=#2c6a1e D=#1f4a16 t=#6a4a28';
const DARKTREE = 'l=#2c5a1e L=#1f4a16 D=#143212 t=#3e2a14';

export const ICONS = {
  mountain: { pal: P(STONE), rows: [
    '.........w..........',
    '........www.........',
    '.......wwWww........',
    '......wwWsWww.......',
    '.....wWssSssWw......',
    '.....sssSSsssS......',
    '....sssSSdSsssS.....',
    '...sssSSddSSsssS....',
    '..sssSSdddSSSsssS...',
    '.sssSSSddddSSSsssS..',
    'sssSSSdddddSSSSsssS.',
  ] },
  'mountain-alt': { pal: P(STONE), rows: [
    '....w.........w.......',
    '...www.......wWw......',
    '..wWWww.....wsSsw.....',
    '..sSsSs....ssSdSss....',
    '.ssSSdSs..ssSSddSss...',
    'ssSSddSSssssSSdddSss..',
    'sSSdddSSSssSSddddSSss.',
  ] },
  hill: { pal: P('g=#5a9a3c G=#4a8a2e d=#86603e D=#6a4a30'), rows: [
    '......gggggg......',
    '....ggGgggGggg....',
    '..gggGggggggGggg..',
    '.dddddddddddddddd.',
    'ddDdddDdddddDddddd',
  ] },
  'hill-alt': { pal: P('g=#5a9a3c G=#4a8a2e d=#86603e D=#6a4a30'), rows: [
    '...gggg.....gggg...',
    '.ggGgggg...ggGggg..',
    'ddddddddd.ddddddddd',
    'dDdddDdddddddDddDdd',
  ] },
  forest: { pal: P(TREE), rows: [
    '..lll......lll......lll..',
    '.lLlll....lLlll....lLlll.',
    'llllLll..llllLll..llllLll',
    'lLlllll..lLlllll..lLlllll',
    '.lllLl....lllLl....lllLl.',
    '...t........t........t...',
    '...t........t........t...',
  ] },
  'forest-alt': { pal: P(DARKTREE), rows: [
    '....L.......L....',
    '...lLl.....lLl...',
    '..llLll...llLll..',
    '...lLl.....lLl...',
    '..llLll...llLll..',
    '.lllLlll.lllLlll.',
    'llllLllllllllLlll',
    '....t.......t....',
    '....t.......t....',
  ] },
  marsh: { pal: P('w=#3466c4 W=#5a8ad8 p=#2e7a2a P=#4a9a3a r=#5a3a20 g=#4a7a2a'), rows: [
    '..r.....r.....r...',
    '..r.g...r..g..r...',
    '.grg...grg....rg..',
    'wwwwwwwwwwwwwwwwww',
    'wWwwppwwwwWwwPpwww',
    'wwwwPpwwwwwwwppwWw',
    'wwWwwwwwpPwwwwwwww',
  ] },
  scrub: { pal: P('l=#4a8a2e L=#3a7a26 y=#e8d84a r=#d04040'), rows: [
    '.l....l.....l...',
    'lLl..lyl...lLl..',
    'lLl..lLl...lrl..',
  ] },
  town: { pal: P('r=#8a2e24 R=#5a1e18 w=#e8dcc0 W=#c8b898 b=#6a4a28 g=#9ad8e8 k=#2a2a2a'), rows: [
    '.....rr.........rr.....',
    '....rrrr.......rrrr....',
    '...rrRRrr.....rrRRrr...',
    '..rrrrrrrr...rrrrrrrr..',
    '..wwwwwwww.r.wwwwwwww..',
    '..wgwwwwgwrrrwgwwwwgw..',
    '..wwwwwwwrrrrrwwwwwww..',
    '..wwwbbwwwWWWwwwbbwww..',
    '..wwwbbwwwgWgwwwbbwww..',
    '..WWWWWWWWWWWWWWWWWWW..',
  ] },
  ithaca: { pal: P('r=#2f4a7a R=#1e2e4a w=#e8dcc0 W=#c8b898 b=#6a4a28 g=#ffd36a k=#2a2a2a f=#c0392b'), rows: [
    '..........f..........',
    '..........ff.........',
    '..........k..........',
    '.........rrr.........',
    '....rr..rrrrr..rr....',
    '...rrrr.wwwww.rrrr...',
    '..rrRRrrwgwgwrrRRrr..',
    '..wwwwwwwwwwwwwwwww..',
    '..wgwwgwwwbwwwgwwgw..',
    '..wwwwwwwwbwwwwwwww..',
    '..WWWWWWWWWWWWWWWWW..',
  ] },
  barrow: { pal: P('y=#dccf9a Y=#c8b880 d=#a8945e k=#3a2a1a g=#f0c419'), rows: [
    '.........g.........',
    '........yyy........',
    '.......yyYyy.......',
    '......yyYYYyy......',
    '.....yyYYdYYyy.....',
    '....yyYYddYYYyy....',
    '...yyYYdkkdYYYyy...',
    '..yyYYddkkddYYYyy..',
    '.yyYYYddkkddYYYYyy.',
    'dddddddddddddddddd.',
  ] },
  church: { pal: P('p=#6ab8aa P=#3f7a70 d=#1c3a36 w=#3466c4 W=#5a8ad8 g=#ffd36a'), rows: [
    '........ppp........',
    '.......pPgPp.......',
    '...pp..ppppp..pp...',
    '..pPPp.pPPPp.pPPp..',
    '.pppppppppppppppp..',
    '.pPdpPdpPdpPdpPdp..',
    '.ppppppppppppppppp.',
    'wwWwwwwwwwwWwwwwwww',
  ] },
  pass: { pal: P(`${STONE} i=#a8cff0 I=#e8f4ff`), rows: [
    '....w.........w.....',
    '...wIw.......wIw....',
    '..wiiIw.....wiiIw...',
    '..sSiis.....sSiis...',
    '.ssSSdSs...ssSSdSs..',
    'ssSSdddSs.ssSSdddSs.',
    'sSSdddddSssSSdddddSs',
  ] },
  copperdeep: { pal: P(`${STONE} c=#c06a3a C=#e8945e o=#4fa38a k=#1a1210 y=#ffd36a`), rows: [
    '.......w.......w.......',
    '......wWw.....wWw......',
    '.....ssSss...ssSss.....',
    '....ssSSdssssSSddss....',
    '...ssSScccccccccSsss...',
    '..ssSSScCcCcCcCcSSsss..',
    '..sSSSScckkkkkccSSSss..',
    '.ssSSSScckyykkccSSSsss.',
    '.sSSSSScckkkkkccSSSSss.',
    'ssSSSSScckkkkkccoSSSsss',
  ] },
  obelisk: { pal: P('b=#b08a3a B=#8a6a2a d=#5a4020 w=#f4ecd8 k=#2a2a2a r=#c0392b'), rows: [
    '.....b.....',
    '....bBb....',
    '...bbBbb...',
    '..bbbbbbb..',
    '..bwwwwwB..',
    '..bwkwkwB..',
    '..bwwkwwB..',
    '..bwwrwwB..',
    '..bwwwwwB..',
    '..bbbbbbB..',
    '..bBdBdBB..',
    '..bBdBdBB..',
    '..bBdBdBB..',
    '.bbbbbbbBB.',
    'bbbbbbbbbBB',
  ] },
  endspire: { pal: P('p=#a678a6 P=#7a4a7a e=#e0e0a8 E=#cfcf94 k=#2a1a2a'), rows: [
    '......pp......',
    '.....pPPp.....',
    '.....pkkp.....',
    '....pppppp....',
    '..pp.pPPp.pp..',
    '..pPppPPppPp..',
    '.....pkkp.....',
    '.....pPPp.....',
    '....pppppp....',
    '...ppPPPPpp...',
    'eeeeeeeeeeeeee',
    'EeeEeeeEeeEeeE',
  ] },
  hall: { pal: P('r=#2f4a7a R=#1e2e4a w=#e8dcc0 W=#c8b898 b=#6a4a28 g=#ffd36a y=#d9b24a'), rows: [
    '........y........',
    '.......rrr.......',
    '......rrRrr......',
    '....rrrRRRrrr....',
    '..rrrrRRRRRrrrr..',
    '.rrrrrrrrrrrrrrr.',
    '..wWwWwWwWwWwWw..',
    '..wgwwwgwwwwgww..',
    '..wwwwwwbbwwwww..',
    '..wgwwwwbbwwgww..',
    '.WWWWWWWWWWWWWWW.',
  ] },
  tents: { pal: P('l=#6a4a28 L=#4a3018 f=#ffb030 F=#ff6a1a y=#fff3a0 s=#5a5a5a'), rows: [
    '......y......',
    '.....yfy.....',
    '....ffyff....',
    '...fFfyfFf...',
    '...fFFfFFf...',
    '..lLlLlLlLl..',
    '.lLlllllllLl.',
    'sssssssssssss',
  ] },
  cave: { pal: P(`${STONE} k=#140c1e K=#2a2030`), rows: [
    '......ssssss......',
    '....ssSSSSSSss....',
    '...sSSSkkkkSSSs...',
    '..sSSSkkKKkkSSSs..',
    '.sSSSkkKKKKkkSSSs.',
    'sSSSSkkKKKKkkSSSSs',
  ] },
  mine: { pal: P('b=#8a5a2c B=#5e3c1a k=#140c1e K=#2a2030 s=#7d7d7d r=#9a9a9a'), rows: [
    '.bbbbbbbbbbbbb.',
    '.BbBBBBBBBBBbB.',
    '.bB.........Bb.',
    '.bBkkkkkkkkkBb.',
    '.bBkKKKKKKKkBb.',
    '.bBkKKKKKKKkBb.',
    '.bBkkkkkkkkkBb.',
    'rsrsrsrsrsrsrsr',
  ] },
  forge: { pal: P('s=#4a4a52 S=#2c2c30 f=#ffb030 F=#ff6a1a y=#fff3a0 c=#c06a3a k=#1a1a1a'), rows: [
    '..........kk..',
    '..........kk..',
    '..ssssssssss..',
    '.sSsSsSsSsSss.',
    '.sSkkkkkkkkSs.',
    '.sSkfFfFfFkSs.',
    '.sSkFyfyfFkSs.',
    '.sSkkkkkkkkSs.',
    '.ssssssssssss.',
    '..cc......cc..',
    '.cccc....cccc.',
  ] },
  fort: { pal: P('w=#6a4a28 W=#4a3018 s=#7d7d7d S=#5a5a5a k=#1a1a1a g=#e0e0e0 r=#2a2a2a'), rows: [
    '..rrrr...',
    '..rgrr...',
    '..r......',
    'swswswsws',
    'sSSSSSSSs',
    '.wWWWWWw.',
    '.wkWWWkw.',
    '.wWWWWWw.',
    '.wWWkWWw.',
    '.wWWWWWw.',
    '.wWkWkWw.',
    '.wWWWWWw.',
    'sssssssss',
  ] },
  city: { pal: P('r=#5a1e18 R=#8a2e24 b=#6a4a28 B=#4a3018 w=#c8b898 g=#ffd36a m=#e8dcc0 k=#2a2a2a'), rows: [
    '.....k...............',
    '.....mm..............',
    '.....mmm.............',
    '.....k........k......',
    '..bbbbbbbbbbbbbbbbb..',
    '...bBbBbBbBbBbBbBb...',
    'wwwwbbbbbbbbbbbbbwwww',
    '.wwwwwwwwwwwwwwwwwww.',
  ] },
  ship: { pal: P('b=#6a4a28 B=#4a3018 s=#e8e2cf S=#c8c0a8 k=#1a1a1a w=#3466c4 W=#5a8ad8 f=#1a1a1a g=#f0f0f0'), rows: [
    '.......kfg.........',
    '.......kff.........',
    '.......k...........',
    '....sssk.ssss......',
    '...sssSk.sssSs.....',
    '...sssSk.sssSs.....',
    '....ssSk..ssSs.....',
    '.......k...........',
    'bbbbbbbbbbbbbbbbb..',
    '.bBbBbBbBbBbBbBbbb.',
    '..bbbbbbbbbbbbbbb..',
    'wwWwwwwwwWwwwwwwwWw',
  ] },
  serpent: { pal: P('p=#8a3a8a P=#a04aa0 s=#e0a0d0 w=#3466c4 W=#5a8ad8'), rows: [
    '.pp............pp...',
    'pPPp..........pPPp..',
    'pPsp...pp.....psPp..',
    '.pPp..pPPp....pPp...',
    '.pPp..psPp...pPp....',
    '..pPp.pPp...pPsp....',
    '..psPpPp....pPp.....',
    'wwwwWwwwwwwwwwwWwwww',
  ] },
  gate: { pal: P('o=#140c1e O=#3a2a5a e=#e0e0a8 k=#000000 s=#a0a0ff'), rows: [
    '.ooooooooo.',
    '.oOOOOOOOo.',
    '.oOkkkkkOo.',
    '.oOkskskOo.',
    '.oOkkskkOo.',
    '.oOkskkkOo.',
    '.oOkkkskOo.',
    '.oOOOOOOOo.',
    '.ooooooooo.',
    'eeeeeeeeeee',
  ] },
  cavemount: { pal: P(`${STONE} k=#0f2a30 c=#3ae0e8 K=#1a3a42`), rows: [
    '........sss.........',
    '......ssSSSss.......',
    '....ssSSdddSSss.....',
    '...sSSddKKKddSSs....',
    '..sSSdKKkkkKKdSSs...',
    '.sSSdKkkckkckKdSSs..',
    'sSSSdKkkkkkkkKdSSSs.',
  ] },
  hoard: { pal: P('b=#8a5a2a B=#a86e3a k=#2a1a0a g=#f0c419 G=#fff6a0 y=#c89a14'), rows: [
    '....gGg...........',
    '...ggyGg..........',
    '..bbbbbbbbbbbb....',
    '..bBBBBBBBBBBb.g..',
    '..kkkkkggkkkkk.Gg.',
    '..bBBBBggBBBBbgyg.',
    '..bBBBBBBBBBBbggG.',
    '..bbbbbbbbbbbb....',
  ] },
  wyrm: { pal: P('o=#140c1e e=#e0e0a8 E=#cfcf94 p=#e070e0 P=#ff9aff w=#ffffff'), rows: [
    '.....p.....',
    '....pPp....',
    '...pPwPp...',
    '....pPp....',
    '.....p.....',
    '.....o.....',
    '....ooo....',
    '....ooo....',
    '....ooo....',
    '...ooooo...',
    'eeeeeeeeeee',
    'EeEeeEeEeeE',
  ] },
  shrine: { pal: P('g=#9ad8e8 G=#e8fbff o=#140c1e k=#3a2a5a b=#5ae0ff w=#ffffff'), rows: [
    '....b....',
    '....b....',
    '....w....',
    '.ggggggg.',
    '.gGGwGGg.',
    '.gGbbbGg.',
    '.gGbwbGg.',
    '.ooooooo.',
    'okokokoko',
  ] },
  trial: { pal: P('c=#c06a3a C=#e8945e o=#4fa38a t=#6c6c62 T=#5a5a52 k=#1a1a1a f=#ffb030'), rows: [
    '.ttttttttttttt.',
    '.tTcccccccccTt.',
    '.tcCcCcCcCcCct.',
    '.tcCkkkkkkkCct.',
    '.tcCkkfkfkkCct.',
    '.tcCkkkfkkkCct.',
    '.tcCkkkkkkkCct.',
    '.tcCcCcCcCcCct.',
    '.tTcccccocccTt.',
    'ttttttttttttttt',
  ] },
  airship: { pal: P('b=#c8b898 B=#a89878 s=#8a5a2c S=#6a4a28 r=#c0392b c=#c06a3a k=#2a2a2a w=#e8e2cf'), rows: [
    '....bbbbbbbbbb.....',
    '..bbBbbBbbBbbBbb...',
    '.bbbbbbbbbbbbbbbbr.',
    '..bbBbbBbbBbbBbb...',
    '....bbbbbbbbbb.....',
    '......k....k.......',
    '......k....k.......',
    '...ssssssssssss....',
    '....SsScScScSsS....',
    '.....ssssssssss....',
  ] },
  compass: { pal: P('r=#c0392b R=#8a1c1c w=#e8e2cf W=#b8b098 k=#2a2a2a g=#d9b24a'), rows: [
    '......gg......',
    '....gwwwwg....',
    '...gwwrwwwg...',
    '..gwwwrrwwwg..',
    '.gwwwwrrwwwwg.',
    'gwwwwwrrwwwwwg',
    'gwwwwwkkwwwwwg',
    'gwwwwwWWwwwwwg',
    '.gwwwwWWwwwwg.',
    '..gwwwWWwwwg..',
    '...gwwwWwwg...',
    '....gwwwwg....',
    '......gg......',
  ] },
};
