// The kit, as 16x16-ish item sprites. One drawing per kind; the grade is the
// material, so a Netherite Sword and a Stone Sword are the same shape in
// different metal. `m` is the material, `M` its highlight, `d` its shadow,
// `h` wood, `k` the dark line inside the sprite.
export const MATERIALS = [
  { name: 'stone', m: '#8a8a8a', M: '#b0b0b0', d: '#5a5a5a' },
  { name: 'copper', m: '#c06a3a', M: '#e8945e', d: '#8a4524' },
  { name: 'iron', m: '#d4d4d4', M: '#ffffff', d: '#959595' },
  { name: 'diamond', m: '#3ad6c6', M: '#a8fff2', d: '#16908a' },
  { name: 'netherite', m: '#4f4549', M: '#776a6f', d: '#2c2427' },
];

export const FIXED = {
  h: '#8a5a2c', H: '#5e3c1a', k: '#241a14', s: '#e8e8e8', w: '#f4ecd8', p: '#7a3aa8', P: '#c38ae8', g: '#f0c419',
};

export const KIT = {
  sword: [
    '.............kk',
    '............kMk',
    '...........kMmk',
    '..........kMmk.',
    '.........kMmk..',
    '........kMmk...',
    '.......kMmk....',
    '..kk..kMmk.....',
    '..kdkkMmk......',
    '...kdMmk.......',
    '....kdk........',
    '...khdk........',
    '..khkkdk.......',
    '.khk...kk......',
    'kHk............',
    'kk.............',
  ],
  axe: [
    '....kkkk.......',
    '...kMMmmk......',
    '..kMmmmmkk.....',
    '..kmmmmmhhk....',
    '..kmmmdkkhk....',
    '..kmmdk.khk....',
    '...kdk...khk...',
    '....k.....khk..',
    '...........khk.',
    '............kHk',
    '.............kk',
  ],
  hammer: [
    '.....kkkkkkk...',
    '....kMMmmmmdk..',
    '....kMmmmmmdk..',
    '....kmmmmmmdk..',
    '.....kkkhkkk...',
    '.......khk.....',
    '.......khk.....',
    '.......khk.....',
    '.......khk.....',
    '.......khk.....',
    '.......khk.....',
    '.......kHk.....',
    '.......kHk.....',
    '.......kkk.....',
  ],
  mace: [
    '.......k.......',
    '.....k.kMk.k...',
    '....kMkMMmkMk..',
    '.....kmMmmmk...',
    '....kMmmmmmdk..',
    '.....kmmmmdk...',
    '....kdkmdkdk...',
    '.......khk.....',
    '.......khk.....',
    '.......khk.....',
    '.......khk.....',
    '.......kHk.....',
    '.......kmk.....',
    '.......kkk.....',
  ],
  bow: [
    '....kkk........',
    '...khhhk.......',
    '..khk..ks......',
    '..kh....s......',
    '.kh.....s......',
    '.kh.....s......',
    '.kmk....s......',
    '.kMk....s......',
    '.kmk....s......',
    '.kh.....s......',
    '.kh.....s......',
    '..kh....s......',
    '..khk..ks......',
    '...khhhk.......',
    '....kkk........',
  ],
  crossbow: [
    '..kkkkkkkkkkk..',
    '.kMmmmmmmmmmdk.',
    '.kkk..khk..kkk.',
    '..s...khk...s..',
    '...s..khk..s...',
    '....s.khk.s....',
    '.....skhks.....',
    '......khk......',
    '......kmk......',
    '......khk......',
    '......khk......',
    '......kHk......',
    '......kkk......',
  ],
  trident: [
    '.k...k...k.....',
    'kMk.kMk.kMk....',
    'kMk.kMk.kMk....',
    'kmkkkmkkkmk....',
    '.kmmmmmmmk.....',
    '..kkkdmkkk.....',
    '.....kdk.......',
    '.....kdk.......',
    '.....kdk.......',
    '.....kdk.......',
    '.....kdk.......',
    '.....kmk.......',
    '.....kMk.......',
    '......k........',
  ],
  shield: [
    '.kkkkkkkkkkkk.',
    'kmmmmmmmmmmmmk',
    'kmhhhhhhhhhhmk',
    'kmhhhhhhhhhhmk',
    'kmhhhhMMhhhhmk',
    'kmhhhMMMMhhhmk',
    'kmhhhhMMhhhhmk',
    'kmhhhhhhhhhhmk',
    'kmhhhhhhhhhhmk',
    '.kmhhhhhhhhmk.',
    '..kmhhhhhhmk..',
    '...kmhhhhmk...',
    '....kmmmmk....',
    '.....kkkk.....',
  ],
  book: [
    '..kkkkkkkkkk..',
    '.kMppppppppMk.',
    '.kpppppppppkw.',
    '.kppPPPPPPpkw.',
    '.kppPppppPpkw.',
    '.kppPPPPPPpkw.',
    '.kppppppppkww.',
    '.kpppPPpppkw..',
    '.kppppppppkw..',
    '.kMppppppMkw..',
    '..kkkkkkkkkw..',
  ],
  helmet: [
    '...kkkkkkkk...',
    '..kMMMmmmmmk..',
    '.kMmmmmmmmmdk.',
    '.kmmmmmmmmmdk.',
    '.kmmkkkkkkmdk.',
    '.kmk......kdk.',
    '.kmk......kdk.',
    '..k........k..',
  ],
  plate: [
    '.kkkk....kkkk.',
    'kmMmmk..kmmMdk',
    'kmmmmmkkmmmmdk',
    'kmmmmmmmmmmmdk',
    '.kkmmmmmmmmkk.',
    '..kMmmmmmmdk..',
    '..kmmmmmmmdk..',
    '..kmmmmmmmdk..',
    '..kmmmmmmmdk..',
    '..kmmmmmmmdk..',
    '..kkkkkkkkkk..',
  ],
  greaves: [
    '.kkkkkkkkkkkk.',
    '.kMmmmmmmmmdk.',
    '.kmmmmmmmmmdk.',
    '.kmmmmkkmmmdk.',
    '.kmmmk..kmmdk.',
    '.kmmmk..kmmdk.',
    '.kmmmk..kmmdk.',
    '.kmmmk..kmmdk.',
    '.kmmdk..kmmdk.',
    '.kkkkk..kkkkk.',
  ],
  boots: [
    '..kkkk....kkkk..',
    '..kMmk....kMmk..',
    '..kmmk....kmmk..',
    '..kmmk....kmmk..',
    '..kmmmkk..kmmmkk',
    '..kmmmmdk.kmmmmdk',
    '..kkkkkkk.kkkkkkk',
  ],
};
