// Generated by tools/prepare-hero-tokens.mjs — do not edit by hand.
//
// Every figure the player may choose, and where it sits on the sheet. The
// pack names an ancestry and a calling and nothing else, so that is the
// choice the game offers: pick your calling, then pick who has it.
// The figures are no longer drawn — your Minecraft skin is (js/skins.js) —
// but a character still carries one in its save, so the list stays.
export const SHEET = null;
export const CELL = 96;
export const COLS = 10;
export const ROWS = 7;

export const LOOKS = [
  {
    "id": "fighter-wayfarer-barbarian",
    "cls": "fighter",
    "col": 0,
    "row": 0,
    "ancestry": "Wayfarer",
    "kind": "Barbarian",
    "gear": "Greataxe"
  },
  {
    "id": "fighter-human-veteran",
    "cls": "fighter",
    "col": 1,
    "row": 0,
    "ancestry": "Human",
    "kind": "Veteran",
    "gear": "Dual, Swords, Crossbow"
  },
  {
    "id": "fighter-dwarf-fighter",
    "cls": "fighter",
    "col": 2,
    "row": 0,
    "ancestry": "Dwarf",
    "kind": "Fighter",
    "gear": "Axe"
  },
  {
    "id": "fighter-smallfolk-barbarian",
    "cls": "fighter",
    "col": 3,
    "row": 0,
    "ancestry": "Smallfolk",
    "kind": "Barbarian",
    "gear": "Greataxe"
  },
  {
    "id": "fighter-half-orc-barbarian",
    "cls": "fighter",
    "col": 4,
    "row": 0,
    "ancestry": "Half-Orc",
    "kind": "Barbarian",
    "gear": "Dual, Axes"
  },
  {
    "id": "fighter-dragonborn-barbarian",
    "cls": "fighter",
    "col": 5,
    "row": 0,
    "ancestry": "Dragonborn",
    "kind": "Barbarian",
    "gear": "Spear"
  },
  {
    "id": "fighter-tiefling-barbarian",
    "cls": "fighter",
    "col": 6,
    "row": 0,
    "ancestry": "Tiefling",
    "kind": "Barbarian",
    "gear": "Battleaxe"
  },
  {
    "id": "fighter-goliath-fighter",
    "cls": "fighter",
    "col": 7,
    "row": 0,
    "ancestry": "Goliath",
    "kind": "Fighter",
    "gear": "Greatsword"
  },
  {
    "id": "fighter-astralfolk-monk",
    "cls": "fighter",
    "col": 8,
    "row": 0,
    "ancestry": "Astralfolk",
    "kind": "Monk",
    "gear": "Unarmed"
  },
  {
    "id": "fighter-bearfolk-monk",
    "cls": "fighter",
    "col": 9,
    "row": 0,
    "ancestry": "Bearfolk",
    "kind": "Monk",
    "gear": "Quarterstaff"
  },
  {
    "id": "fighter-birdfolk-fighter",
    "cls": "fighter",
    "col": 0,
    "row": 1,
    "ancestry": "Birdfolk",
    "kind": "Fighter",
    "gear": "Crossbow"
  },
  {
    "id": "fighter-bugfolk-fighter",
    "cls": "fighter",
    "col": 1,
    "row": 1,
    "ancestry": "Bugfolk",
    "kind": "Fighter",
    "gear": "Spear, Sword, Dagger"
  },
  {
    "id": "paladin-wayfarer-paladin",
    "cls": "paladin",
    "col": 2,
    "row": 1,
    "ancestry": "Wayfarer",
    "kind": "Paladin",
    "gear": "Sword, Shield"
  },
  {
    "id": "paladin-human-valkyrie",
    "cls": "paladin",
    "col": 3,
    "row": 1,
    "ancestry": "Human",
    "kind": "Valkyrie",
    "gear": "Spear, Shield"
  },
  {
    "id": "paladin-smallfolk-paladin",
    "cls": "paladin",
    "col": 4,
    "row": 1,
    "ancestry": "Smallfolk",
    "kind": "Paladin",
    "gear": "Sword, Shield"
  },
  {
    "id": "paladin-dragonborn-paladin",
    "cls": "paladin",
    "col": 5,
    "row": 1,
    "ancestry": "Dragonborn",
    "kind": "Paladin",
    "gear": "Sword, Shield"
  },
  {
    "id": "paladin-automaton-paladin",
    "cls": "paladin",
    "col": 6,
    "row": 1,
    "ancestry": "Automaton",
    "kind": "Paladin",
    "gear": "Warhammer, Shield"
  },
  {
    "id": "paladin-centaur-paladin",
    "cls": "paladin",
    "col": 7,
    "row": 1,
    "ancestry": "Centaur",
    "kind": "Paladin",
    "gear": "Spear, Shield"
  },
  {
    "id": "paladin-wayfarer-paladin-2",
    "cls": "paladin",
    "col": 8,
    "row": 1,
    "ancestry": "Wayfarer",
    "kind": "Paladin",
    "gear": "Warhammer, Shield"
  },
  {
    "id": "paladin-human-knight",
    "cls": "paladin",
    "col": 9,
    "row": 1,
    "ancestry": "Human",
    "kind": "Knight",
    "gear": "Longsword"
  },
  {
    "id": "paladin-smallfolk-paladin-2",
    "cls": "paladin",
    "col": 0,
    "row": 2,
    "ancestry": "Smallfolk",
    "kind": "Paladin",
    "gear": "Warhammer, Shield"
  },
  {
    "id": "mage-wayfarer-sorcerer",
    "cls": "mage",
    "col": 1,
    "row": 2,
    "ancestry": "Wayfarer",
    "kind": "Sorcerer",
    "gear": "Fire"
  },
  {
    "id": "mage-human-archmage",
    "cls": "mage",
    "col": 2,
    "row": 2,
    "ancestry": "Human",
    "kind": "Archmage",
    "gear": "Lightning"
  },
  {
    "id": "mage-elf-warlock",
    "cls": "mage",
    "col": 3,
    "row": 2,
    "ancestry": "Elf",
    "kind": "Warlock",
    "gear": "Staff"
  },
  {
    "id": "mage-dwarf-wizard",
    "cls": "mage",
    "col": 4,
    "row": 2,
    "ancestry": "Dwarf",
    "kind": "Wizard",
    "gear": "Orb"
  },
  {
    "id": "mage-smallfolk-sorcerer",
    "cls": "mage",
    "col": 5,
    "row": 2,
    "ancestry": "Smallfolk",
    "kind": "Sorcerer",
    "gear": "Fire"
  },
  {
    "id": "mage-half-orc-warlock",
    "cls": "mage",
    "col": 6,
    "row": 2,
    "ancestry": "Half-Orc",
    "kind": "Warlock",
    "gear": "Scepter"
  },
  {
    "id": "mage-dragonborn-wizard",
    "cls": "mage",
    "col": 7,
    "row": 2,
    "ancestry": "Dragonborn",
    "kind": "Wizard",
    "gear": "Staff, Frost"
  },
  {
    "id": "mage-tiefling-wizard",
    "cls": "mage",
    "col": 8,
    "row": 2,
    "ancestry": "Tiefling",
    "kind": "Wizard",
    "gear": "Staff"
  },
  {
    "id": "mage-planetouched-artificer",
    "cls": "mage",
    "col": 9,
    "row": 2,
    "ancestry": "Planetouched",
    "kind": "Artificer",
    "gear": "Crossbow, Shield"
  },
  {
    "id": "mage-goliath-spellcaster",
    "cls": "mage",
    "col": 0,
    "row": 3,
    "ancestry": "Goliath",
    "kind": "Spellcaster",
    "gear": ""
  },
  {
    "id": "mage-foxfolk-spellcaster",
    "cls": "mage",
    "col": 1,
    "row": 3,
    "ancestry": "Foxfolk",
    "kind": "Spellcaster",
    "gear": ""
  },
  {
    "id": "mage-kobold-mage",
    "cls": "mage",
    "col": 2,
    "row": 3,
    "ancestry": "Kobold",
    "kind": "Mage",
    "gear": "Staff"
  },
  {
    "id": "ranger-wayfarer-druid",
    "cls": "ranger",
    "col": 3,
    "row": 3,
    "ancestry": "Wayfarer",
    "kind": "Druid",
    "gear": "Staff"
  },
  {
    "id": "ranger-human-archer",
    "cls": "ranger",
    "col": 4,
    "row": 3,
    "ancestry": "Human",
    "kind": "Archer",
    "gear": "Bow"
  },
  {
    "id": "ranger-elf-scout",
    "cls": "ranger",
    "col": 5,
    "row": 3,
    "ancestry": "Elf",
    "kind": "Scout",
    "gear": "Bow, Sword"
  },
  {
    "id": "ranger-dwarf-ranger",
    "cls": "ranger",
    "col": 6,
    "row": 3,
    "ancestry": "Dwarf",
    "kind": "Ranger",
    "gear": "Bow"
  },
  {
    "id": "ranger-smallfolk-druid",
    "cls": "ranger",
    "col": 7,
    "row": 3,
    "ancestry": "Smallfolk",
    "kind": "Druid",
    "gear": "Staff"
  },
  {
    "id": "ranger-half-orc-ranger",
    "cls": "ranger",
    "col": 8,
    "row": 3,
    "ancestry": "Half-Orc",
    "kind": "Ranger",
    "gear": "Bow"
  },
  {
    "id": "ranger-dragonborn-ranger",
    "cls": "ranger",
    "col": 9,
    "row": 3,
    "ancestry": "Dragonborn",
    "kind": "Ranger",
    "gear": "Bow"
  },
  {
    "id": "ranger-automaton-ranger",
    "cls": "ranger",
    "col": 0,
    "row": 4,
    "ancestry": "Automaton",
    "kind": "Ranger",
    "gear": "Dual, Swords, Bow"
  },
  {
    "id": "ranger-birdfolk-archer",
    "cls": "ranger",
    "col": 1,
    "row": 4,
    "ancestry": "Birdfolk",
    "kind": "Archer",
    "gear": "Bow"
  },
  {
    "id": "ranger-catfolk-ranger",
    "cls": "ranger",
    "col": 2,
    "row": 4,
    "ancestry": "Catfolk",
    "kind": "Ranger",
    "gear": "Bow"
  },
  {
    "id": "ranger-centaur-ranger",
    "cls": "ranger",
    "col": 3,
    "row": 4,
    "ancestry": "Centaur",
    "kind": "Ranger",
    "gear": "Bow"
  },
  {
    "id": "ranger-deerfolk-druid",
    "cls": "ranger",
    "col": 4,
    "row": 4,
    "ancestry": "Deerfolk",
    "kind": "Druid",
    "gear": "Staff"
  },
  {
    "id": "rogue-wayfarer-bard",
    "cls": "rogue",
    "col": 5,
    "row": 4,
    "ancestry": "Wayfarer",
    "kind": "Bard",
    "gear": "Rapier"
  },
  {
    "id": "rogue-human-assassin",
    "cls": "rogue",
    "col": 6,
    "row": 4,
    "ancestry": "Human",
    "kind": "Assassin",
    "gear": "Dagger, Crossbow"
  },
  {
    "id": "rogue-dwarf-bard",
    "cls": "rogue",
    "col": 7,
    "row": 4,
    "ancestry": "Dwarf",
    "kind": "Bard",
    "gear": "Dagger, Bagpipes"
  },
  {
    "id": "rogue-smallfolk-bard",
    "cls": "rogue",
    "col": 8,
    "row": 4,
    "ancestry": "Smallfolk",
    "kind": "Bard",
    "gear": "Rapier"
  },
  {
    "id": "rogue-half-orc-rogue",
    "cls": "rogue",
    "col": 9,
    "row": 4,
    "ancestry": "Half-Orc",
    "kind": "Rogue",
    "gear": "Shortswords"
  },
  {
    "id": "rogue-tiefling-bard",
    "cls": "rogue",
    "col": 0,
    "row": 5,
    "ancestry": "Tiefling",
    "kind": "Bard",
    "gear": "Flute"
  },
  {
    "id": "rogue-planetouched-rogue",
    "cls": "rogue",
    "col": 1,
    "row": 5,
    "ancestry": "Planetouched",
    "kind": "Rogue",
    "gear": "Bow"
  },
  {
    "id": "rogue-birdfolk-bard",
    "cls": "rogue",
    "col": 2,
    "row": 5,
    "ancestry": "Birdfolk",
    "kind": "Bard",
    "gear": "Rapier, Lute"
  },
  {
    "id": "rogue-catfolk-rogue",
    "cls": "rogue",
    "col": 3,
    "row": 5,
    "ancestry": "Catfolk",
    "kind": "Rogue",
    "gear": "Dagger"
  },
  {
    "id": "rogue-harefolk-rogue",
    "cls": "rogue",
    "col": 4,
    "row": 5,
    "ancestry": "Harefolk",
    "kind": "Rogue",
    "gear": "Rapier"
  },
  {
    "id": "rogue-satyr-bard",
    "cls": "rogue",
    "col": 5,
    "row": 5,
    "ancestry": "Satyr",
    "kind": "Bard",
    "gear": "Flute, Dagger"
  },
  {
    "id": "rogue-serpentfolk-rogue",
    "cls": "rogue",
    "col": 6,
    "row": 5,
    "ancestry": "Serpentfolk",
    "kind": "Rogue",
    "gear": "Dual, Daggers"
  },
  {
    "id": "cleric-wayfarer-cleric",
    "cls": "cleric",
    "col": 7,
    "row": 5,
    "ancestry": "Wayfarer",
    "kind": "Cleric",
    "gear": "Holy Symbol, Shield"
  },
  {
    "id": "cleric-human-acolyte",
    "cls": "cleric",
    "col": 8,
    "row": 5,
    "ancestry": "Human",
    "kind": "Acolyte",
    "gear": "Mace, Tome"
  },
  {
    "id": "cleric-elf-cleric",
    "cls": "cleric",
    "col": 9,
    "row": 5,
    "ancestry": "Elf",
    "kind": "Cleric",
    "gear": "Mace, Shield"
  },
  {
    "id": "cleric-dwarf-cleric",
    "cls": "cleric",
    "col": 0,
    "row": 6,
    "ancestry": "Dwarf",
    "kind": "Cleric",
    "gear": "Hammer, Shield"
  },
  {
    "id": "cleric-smallfolk-cleric",
    "cls": "cleric",
    "col": 1,
    "row": 6,
    "ancestry": "Smallfolk",
    "kind": "Cleric",
    "gear": "Holy Symbol, Shield"
  },
  {
    "id": "cleric-half-orc-cleric",
    "cls": "cleric",
    "col": 2,
    "row": 6,
    "ancestry": "Half-Orc",
    "kind": "Cleric",
    "gear": "Mace, Shield"
  },
  {
    "id": "cleric-gnoll-cleric",
    "cls": "cleric",
    "col": 3,
    "row": 6,
    "ancestry": "Gnoll",
    "kind": "Cleric",
    "gear": "Sickle"
  },
  {
    "id": "cleric-wayfarer-cleric-2",
    "cls": "cleric",
    "col": 4,
    "row": 6,
    "ancestry": "Wayfarer",
    "kind": "Cleric",
    "gear": "Mace, Shield"
  },
  {
    "id": "cleric-human-priest",
    "cls": "cleric",
    "col": 5,
    "row": 6,
    "ancestry": "Human",
    "kind": "Priest",
    "gear": "Mace"
  },
  {
    "id": "cleric-smallfolk-cleric-2",
    "cls": "cleric",
    "col": 6,
    "row": 6,
    "ancestry": "Smallfolk",
    "kind": "Cleric",
    "gear": "Mace, Shield"
  },
  {
    "id": "cleric-gnoll-cleric-2",
    "cls": "cleric",
    "col": 7,
    "row": 6,
    "ancestry": "Gnoll",
    "kind": "Cleric",
    "gear": "Sickle"
  },
  {
    "id": "cleric-human-priest-2",
    "cls": "cleric",
    "col": 8,
    "row": 6,
    "ancestry": "Human",
    "kind": "Priest",
    "gear": "Mace"
  }
];

export function looksFor(classId) {
  return LOOKS.filter((look) => look.cls === classId);
}

export function lookById(id) {
  return LOOKS.find((look) => look.id === id) || null;
}

// What a character wears when nobody has chosen, and the fallback when a save
// names a figure that is no longer on the sheet.
export function defaultLook(classId) {
  return looksFor(classId)[0] || LOOKS[0];
}
